plugins {
    id 'java'
}

repositories {
    maven { url = 'https://repo.runelite.net' }
    mavenCentral()
}

def runeLiteVersion = 'latest.release'
dependencies {
    compileOnly "net.runelite:client:${runeLiteVersion}"
    testImplementation "net.runelite:client:${runeLiteVersion}"
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:4.11.0'
}

group = 'com.contextuallogbasket'
version = '1.0.0'
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(11)
}
tasks.register('run', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.contextuallogbasket.PluginLauncher'
    jvmArgs '-ea'
    args '--developer-mode', '--debug'
}
